//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.mart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public string Remarks { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string StreetNumber { get; set; }
        public string CustomerUserName { get; set; }
        public string Shop_Code { get; set; }
        public string Postal_Code { get; set; }
    }
}
