//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.mart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_Id { get; set; }
        public System.DateTime Order_Date { get; set; }
        public int Order_Total { get; set; }
        public int Order_Status { get; set; }
        public string Customer_Id { get; set; }
        public Nullable<System.DateTime> Delivered_Date { get; set; }
        public string Shop_Code { get; set; }
        public int Product_Id { get; set; }
        public int Order_Quantity { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
