//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.mart
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopDetail()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Shop_Id { get; set; }
        public string Shop_Code { get; set; }
        public string ShopName { get; set; }
        public string ShopKeeperName { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Shop_Domain_Name { get; set; }
        public string Pin_Code { get; set; }
        public string AspNetUsersId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
